# StatefulSet for mail core service
---
kind: StatefulSet
apiVersion: apps/v1beta1
metadata:
  name: mailman-core
  namespace: mail
  labels:
    app: mail-suit-service
spec:
  serviceName: mail-suit-service
  replicas: 1
  selector:
    matchLabels:
      app: mail-suit-service
  template:
    metadata:
      labels:
        app: mail-suit-service
    spec:
      containers:
        - name: mailman-core
          image: swr.cn-north-1.myhuaweicloud.com/openeuler/mail-core:v0.1.0
          imagePullPolicy: "IfNotPresent"
          volumeMounts:
            - mountPath: /opt/mailman/
              name: mailman-core-volume
          env:
            - name: DATABASE_URL
              value: postgres://mailman:mailmanpass@mailman-database-0.mail-suit-service.mail.svc.cluster.local/mailmandb
            - name: DATABASE_TYPE
              value: postgres
            - name: DATABASE_CLASS
              value: mailman.database.postgresql.PostgreSQLDatabase
            - name: HYPERKITTY_API_KEY
              valueFrom:
                secretKeyRef:
                  name: mailsecret
                  key: HYPERKITTY_API_KEY
            - name: HYPERKITTY_URL
            # NOTE: Please update the HYPERKITTY_URL
              value: http://mailman-web-service.mail.svc.cluster.local:8000/hyperkitty
            - name: SMTP_HOST
              value: mailman-exim4-service.mail.svc.cluster.local
          # Sed command is used here to force change default charsets to UTF-8
          # related issue: https://gitlab.com/mailman/postorius/issues/325
          command:
            - /bin/sh
            - -c
            - |
              sed -i "s/charset: us-ascii/charset: utf-8/g" /usr/lib/python3.6/site-packages/mailman/config/schema.cfg;
              exec docker-entrypoint.sh master --force
      #NOTE: Empty dir can't be used in a production dir. Please upgrade it before using.
      volumes:
        - name: mailman-core-volume
          persistentVolumeClaim:
            claimName: config-vol
